## Clock signal
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]

##Pmod Header JB
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports ss]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports MISO]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports sck]

##Buttons
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports rst]

##Audio out
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports PWM]

set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports {swt[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[0]}]
set_property PACKAGE_PIN J15 [get_ports {swt[0]}]
set_property PACKAGE_PIN L16 [get_ports {swt[1]}]
set_property PACKAGE_PIN M13 [get_ports {swt[2]}]
set_property PACKAGE_PIN R15 [get_ports {swt[3]}]
set_property PACKAGE_PIN R17 [get_ports {swt[4]}]
set_property PACKAGE_PIN T18 [get_ports {swt[5]}]
set_property PACKAGE_PIN U18 [get_ports {swt[6]}]
set_property PACKAGE_PIN R13 [get_ports {swt[7]}]
set_property PACKAGE_PIN T8 [get_ports {swt[8]}]
set_property PACKAGE_PIN U8 [get_ports {swt[9]}]
set_property PACKAGE_PIN R16 [get_ports {swt[10]}]
set_property PACKAGE_PIN T13 [get_ports {swt[11]}]


set_property MARK_DEBUG false [get_nets {control/data_out[0]}]
set_property MARK_DEBUG false [get_nets {control/data_out[2]}]
set_property MARK_DEBUG false [get_nets {control/data_out[6]}]
set_property MARK_DEBUG false [get_nets {control/data_out[8]}]
set_property MARK_DEBUG false [get_nets {control/data_out[9]}]
set_property MARK_DEBUG false [get_nets {control/data_out[10]}]
set_property MARK_DEBUG false [get_nets {control/data_out[1]}]
set_property MARK_DEBUG false [get_nets {control/data_out[3]}]
set_property MARK_DEBUG false [get_nets {control/data_out[4]}]
set_property MARK_DEBUG false [get_nets {control/data_out[5]}]
set_property MARK_DEBUG false [get_nets {control/data_out[7]}]
set_property MARK_DEBUG false [get_nets {control/data_out[11]}]

set_property MARK_DEBUG true [get_nets {led_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[9]}]
set_property MARK_DEBUG true [get_nets {led_OBUF[11]}]
set_property MARK_DEBUG true [get_nets ss_OBUF]


set_property MARK_DEBUG true [get_nets MISO_IBUF]


set_property MARK_DEBUG true [get_nets sck_OBUF]
connect_debug_port u_ila_0/probe1 [get_nets [list {debug_data[0]} {debug_data[1]} {debug_data[2]} {debug_data[3]} {debug_data[4]} {debug_data[5]} {debug_data[6]} {debug_data[7]} {debug_data[8]} {debug_data[9]} {debug_data[10]} {debug_data[11]}]]


set_property MARK_DEBUG true [get_nets PWM_OBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 11 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {led_OBUF[0]} {led_OBUF[1]} {led_OBUF[2]} {led_OBUF[3]} {led_OBUF[4]} {led_OBUF[5]} {led_OBUF[6]} {led_OBUF[7]} {led_OBUF[8]} {led_OBUF[9]} {led_OBUF[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list MISO_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list PWM_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list sck_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list ss_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
