# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/design_1_fft_chain_wrapper_0_0.xci
# IP: The module: 'design_1_fft_chain_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/fft_chain_xfft_0_1/fft_chain_xfft_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_chain_xfft_0_1 || ORIG_REF_NAME==fft_chain_xfft_0_1} -quiet] -quiet

# IP: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/fft_chain_xfft_1_1/fft_chain_xfft_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_chain_xfft_1_1 || ORIG_REF_NAME==fft_chain_xfft_1_1} -quiet] -quiet

# XDC: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/Nexys_4_DDR_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fft_chain_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/fft_chain_ooc.xdc

# IP: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/design_1_fft_chain_wrapper_0_0.xci
# IP: The module: 'design_1_fft_chain_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/fft_chain_xfft_0_1/fft_chain_xfft_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_chain_xfft_0_1 || ORIG_REF_NAME==fft_chain_xfft_0_1} -quiet] -quiet

# IP: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/fft_chain_xfft_1_1/fft_chain_xfft_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_chain_xfft_1_1 || ORIG_REF_NAME==fft_chain_xfft_1_1} -quiet] -quiet

# XDC: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/Nexys_4_DDR_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fft_chain_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/fengbin3/TFT_keyboard/TFT.srcs/sources_1/bd/design_1/ip/design_1_fft_chain_wrapper_0_0/src/fft_chain_ooc.xdc
