set_property SRC_FILE_INFO {cfile:D:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/constrs_1/new/eth_ref_clk.xdc rfile:../../../TCP_Client.srcs/constrs_1/new/eth_ref_clk.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/constrs_1/new/external_io.xdc rfile:../../../TCP_Client.srcs/constrs_1/new/external_io.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports eth_ref_clk]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {gpio_io_i_1[0]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports {gpio_io_i_2[0]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {gpio_io_i_3[0]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports {gpio_io_i_4[0]}]
