# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1.xci
# IP: The module: 'TCP_Client_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TCP_Client_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TCP_Client_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'TCP_Client_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1.xci
# IP: The module: 'TCP_Client_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TCP_Client_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TCP_Client_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ECE532_Project/WarmUp_Demo/TCP_Client/TCP_Client.srcs/sources_1/bd/TCP_Client/ip/TCP_Client_axi_gpio_0_1/TCP_Client_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'TCP_Client_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
